groups:
  - name: sentiment_analysis_alerts
    rules:
      - alert: HighMemoryUsage
        expr: sentiment_memory_usage_bytes > 40800000000  # 40.8GB
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High memory usage detected
          description: Memory usage is above 40.8GB for 5 minutes

      - alert: HighErrorRate
        expr: rate(sentiment_errors_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High error rate detected
          description: Error rate is above 5% for 2 minutes

      - alert: PoorAttributionQuality
        expr: |
          (sentiment_attribution_entropy < 0.5 or sentiment_attribution_entropy > 2.5)
          or
          (sentiment_attribution_sparsity < 0.1 or sentiment_attribution_sparsity > 0.9)
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Poor attribution quality detected
          description: Attribution metrics are outside acceptable ranges for 5 minutes

      - alert: HighLatency
        expr: sentiment_request_latency_seconds{quantile="0.95"} > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High request latency detected
          description: 95th percentile latency is above 1 second for 2 minutes

      - alert: LowCacheHitRate
        expr: |
          sum(rate(sentiment_cache_hits_total[5m])) 
          / 
          sum(rate(sentiment_cache_requests_total[5m])) < 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Low cache hit rate detected
          description: Cache hit rate is below 50% for 5 minutes
