global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'  # Set via environment variable

# The root route on which each incoming alert enters.
route:
  # The root route must not have any matchers as it is the entry point for all alerts
  receiver: 'slack-notifications'
  
  # Group alerts by cluster and alertname
  group_by: ['category', 'severity']
  
  # How long to wait to buffer alerts of the same group before sending
  group_wait: 30s
  
  # How long to wait before sending a notification about new alerts that are in the same group
  group_interval: 5m
  
  # How long to wait before sending a notification again if it has already been sent successfully
  repeat_interval: 4h

  # Child routes for different severity levels
  routes:
    # Critical alerts route
    - receiver: 'slack-critical'
      matchers:
        - severity = "critical"
      group_wait: 10s  # Shorter wait for critical alerts
      group_interval: 1m
      repeat_interval: 1h
    
    # Warning alerts route
    - receiver: 'slack-warnings'
      matchers:
        - severity = "warning"
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

# Inhibition rules allow suppressing alerts based on the presence of other alerts
inhibit_rules:
  # Don't send warning alerts if there's already a critical alert for the same category
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ['category']

receivers:
  - name: 'slack-notifications'  # Default receiver
    slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        footer: '{{ template "slack.footer" . }}'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '{{ (index .Alerts 0).Annotations.dashboard }}'
  
  - name: 'slack-critical'  # Critical alerts receiver
    slack_configs:
      - channel: '#monitoring-critical'
        send_resolved: true
        title: '🚨 {{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        footer: '{{ template "slack.footer" . }}'
        color: 'danger'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '{{ (index .Alerts 0).Annotations.dashboard }}'
  
  - name: 'slack-warnings'  # Warning alerts receiver
    slack_configs:
      - channel: '#monitoring-warnings'
        send_resolved: true
        title: '⚠️ {{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        footer: '{{ template "slack.footer" . }}'
        color: 'warning'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '{{ (index .Alerts 0).Annotations.dashboard }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'
