groups:
  - name: performance_alerts
    rules:
      # Performance Regression Alerts
      - alert: CriticalPerformanceRegression
        expr: performance_regression_score < -0.8
        for: 5m
        labels:
          severity: critical
          category: performance
        annotations:
          summary: Critical performance regression detected
          description: Performance regression score is {{ $value }} (threshold -0.8)
          dashboard: https://grafana:3000/d/redis-benchmarks
      
      - alert: PerformanceRegression
        expr: performance_regression_score < -0.5
        for: 10m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: Performance regression detected
          description: Performance regression score is {{ $value }} (threshold -0.5)
          dashboard: https://grafana:3000/d/redis-benchmarks

      # Latency Alerts
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(redis_operation_latency_seconds_bucket[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
          category: latency
        annotations:
          summary: High operation latency detected
          description: P95 latency is {{ $value }}s (threshold 0.1s)
          dashboard: https://grafana:3000/d/redis-benchmarks

      - alert: CriticalLatency
        expr: histogram_quantile(0.95, rate(redis_operation_latency_seconds_bucket[5m])) > 0.5
        for: 2m
        labels:
          severity: critical
          category: latency
        annotations:
          summary: Critical operation latency detected
          description: P95 latency is {{ $value }}s (threshold 0.5s)
          dashboard: https://grafana:3000/d/redis-benchmarks

  - name: resource_alerts
    rules:
      # Memory Usage Alerts
      - alert: HighMemoryUsage
        expr: redis_memory_usage_bytes / 1024 / 1024 > 1024  # 1GB
        for: 5m
        labels:
          severity: warning
          category: resource
        annotations:
          summary: High memory usage detected
          description: Memory usage is {{ $value | humanize }}B (threshold 1GB)
          dashboard: https://grafana:3000/d/redis-benchmarks

      - alert: CriticalMemoryUsage
        expr: redis_memory_usage_bytes / 1024 / 1024 > 2048  # 2GB
        for: 2m
        labels:
          severity: critical
          category: resource
        annotations:
          summary: Critical memory usage detected
          description: Memory usage is {{ $value | humanize }}B (threshold 2GB)
          dashboard: https://grafana:3000/d/redis-benchmarks

      # Connection Pool Alerts
      - alert: HighConnectionPoolUsage
        expr: redis_connection_pool_size > 80
        for: 5m
        labels:
          severity: warning
          category: resource
        annotations:
          summary: High connection pool usage
          description: Connection pool size is {{ $value }} (threshold 80)
          dashboard: https://grafana:3000/d/redis-benchmarks

  - name: error_alerts
    rules:
      # Error Rate Alerts
      - alert: HighErrorRate
        expr: |
          sum(rate(redis_operations_total{status="failure"}[5m]))
          /
          sum(rate(redis_operations_total[5m])) > 0.05  # 5%
        for: 5m
        labels:
          severity: warning
          category: errors
        annotations:
          summary: High error rate detected
          description: Error rate is {{ $value | humanizePercentage }} (threshold 5%)
          dashboard: https://grafana:3000/d/redis-benchmarks

      - alert: CriticalErrorRate
        expr: |
          sum(rate(redis_operations_total{status="failure"}[5m]))
          /
          sum(rate(redis_operations_total[5m])) > 0.1  # 10%
        for: 2m
        labels:
          severity: critical
          category: errors
        annotations:
          summary: Critical error rate detected
          description: Error rate is {{ $value | humanizePercentage }} (threshold 10%)
          dashboard: https://grafana:3000/d/redis-benchmarks

  - name: availability_alerts
    rules:
      # Cache Hit Rate Alerts
      - alert: LowCacheHitRate
        expr: redis_cache_hit_ratio < 0.8  # 80%
        for: 15m
        labels:
          severity: warning
          category: availability
        annotations:
          summary: Low cache hit rate detected
          description: Cache hit rate is {{ $value | humanizePercentage }} (threshold 80%)
          dashboard: https://grafana:3000/d/redis-benchmarks

      # System Availability Alerts
      - alert: ServiceUnavailable
        expr: up{job="metrics-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          category: availability
        annotations:
          summary: Metrics exporter service is down
          description: Service has been down for more than 1 minute
          dashboard: https://grafana:3000/d/redis-benchmarks
