default: &default_config
  python_version: '3.11'
  redis_version: '7.2'
  test_iterations: 3
  pipeline:
    batch_size: 1000
    num_batches: 10
  memory:
    max_keys: 10000
    value_size_bytes: 1024
  latency:
    num_operations: 1000
    warmup_iterations: 2

staging:
  <<: *default_config
  benchmark_timeout: 1800  # 30 minutes
  test_iterations: 3
  redis:
    maxmemory: 25769803776  # 24GB
    maxmemory_policy: 'allkeys-lru'
    save_interval: 300  # 5 minutes
    databases: 8
  pipeline:
    batch_size: 5000
    num_batches: 20
    timeout: 30
  memory:
    max_keys: 50000
    value_size_bytes: 2048
  latency:
    num_operations: 5000
    warmup_iterations: 5
  thresholds:
    regression_confidence: 0.90  # 90% confidence for staging
    performance_degradation: 0.30  # 30% degradation threshold
    error_rate: 0.08  # 8% error rate threshold
    memory_usage: 0.75  # 75% memory usage threshold

production:
  <<: *default_config
  benchmark_timeout: 3600  # 60 minutes
  test_iterations: 5
  redis:
    maxmemory: 51539607552  # 48GB
    maxmemory_policy: 'allkeys-lru'
    save_interval: 900  # 15 minutes
    databases: 16
  pipeline:
    batch_size: 10000
    num_batches: 50
    timeout: 60
  memory:
    max_keys: 100000
    value_size_bytes: 4096
  latency:
    num_operations: 10000
    warmup_iterations: 10
  thresholds:
    regression_confidence: 0.95  # 95% confidence for production
    performance_degradation: 0.20  # 20% degradation threshold
    error_rate: 0.05  # 5% error rate threshold
    memory_usage: 0.85  # 85% memory usage threshold

ci:
  <<: *default_config
  benchmark_timeout: 900  # 15 minutes
  test_iterations: 2
  redis:
    maxmemory: 1073741824  # 1GB
    maxmemory_policy: 'allkeys-lru'
    save_interval: 0  # Disable persistence
    databases: 4
  pipeline:
    batch_size: 1000
    num_batches: 5
    timeout: 15
  memory:
    max_keys: 10000
    value_size_bytes: 1024
  latency:
    num_operations: 1000
    warmup_iterations: 2
  thresholds:
    regression_confidence: 0.80  # 80% confidence for CI
    performance_degradation: 0.40  # 40% degradation threshold
    error_rate: 0.10  # 10% error rate threshold
    memory_usage: 0.90  # 90% memory usage threshold
